### ISSUE TITLE
TextureFX issue collection

### ISSUE THREAD

**Issue by joreg** [vvvv/VL.Stride#444]
General
- [x] #524
- [x] #502
- [x] #501
- [x] Should the fader for Mix() be a float4?
- [x] Pin order has changed, see Keying help patch
- [x] make sure default sampler is Linear, AddressUVW=wrap. and then remove node: AssignDefaultSampler
- [x] #483
- [x] Custom Texture input doesn't work? See Halo (Gradient)
- [x] add GenerateMipmaps attribute #215 
- [x] For sources with Renderformat set to Unorm subsequent filters fail
- [x] Placing any filter in the patch results in a runtime error: Attempted to divide by zero
- [x] Sort out InTex() vs. Sample() see https://github.com/vvvv/VL.Stride/issues/314#issuecomment-740670398
- [x] missing ToGamma in pipeline
- [x] export doesn't seem to find texturefx nodes 
- [x] Control input for Filters and Mixers for per-pixel modulation
- [x] make "TextureSource" attribute @tebjan 
- [x] create Tunnels node: Rightclicking type enum pin -> throws exception @tebjan 
- [x] Base shader change doesn't trigger node recompile

Nodes
- [x] ChangeFormat needs an sRGB path
- [x] DirectionalBlur has custom control texture
- [x] Implement conversion details as discussed in https://github.com/vvvv/VL.Stride/pull/395
- [x] Move gimmick nodes to external package? Currently slows down startup and parsing a lot. see also #438
- [x] no good standard Blur node yet, only BoxBlur and obscure ones, activate strides gaussian blur
- [x] Don't use dynamic loops in blur shader code, use dynamic defines or different implementations
- [x] Format of sources should be sRGB?!
- [x] Replace Blend with stride binary operator
- [x] Should keying inherit from FilterBase?

**Comment by joreg** [comment]
@tebjan to reproduce: "Pin order sometimes wrong and SetValue calls the wrong pin"

* open help of blurglow
* replace blurglow with blur
* rightclick apply pin of blur -> Error: Unable to cast object of type 'System.Boolean' to type 'VL.Stride.Shaders.ShaderFX.SetVar`1[Stride.Core.Mathematics.Vector4]'.

**Comment by joreg** [comment]
https://github.com/vvvv/VL.Stride/pull/395

core utils
- [ ] Resize (Absolut) -> input is Size (int2), add bicubic mode
- [ ] Resize (Relative) -> input is Factor (float2), add bicubic mode
- [ ] Crop -> inputs in pixels: Left, Top, Right, Bottom
- [ ] ChangeFormat -> see PR395, add tag: convert
- [x] ChannelKeying
- [x] ChromaKey
- [x] LumaKey
- [ ] HSCB -> add tags: hue, saturation, contrast, brightness
- [x] Invert
- [ ] Transform -> use custom sampler input to have it visible by default
- [ ] Threshold -> rename color inputs to "Output Color A"...
- [x] LinearDepth
- [x] Levels
- [ ] Coordinates -> consider splitting in 2
- [x] Median
- [x] BackgroundSubstraction
- [ ] TextureInfo -> rename to (Advanced)?, also remove version from (Basic)

core sources
- [x] Color
- [x] Gradient
- [x] Noise
- [x] Halo
- [ ] Halo (Gradient)

core artistic filters
- [ ] Blur -> replace input2 with Control input
- [ ] DirectionalBlur -> replace input2 with Control input
- [x] BlurGlow
- [x] BlurPerfector
- [ ] BoxBlur -> consider removing
- [x] Sharpen
- [x] Edge
- [x] Mosaic
- [x] Metallica
- [x] Glow
- [x] Bump
- [x] Colorize
- [x] MapColor
- [x] DropShadow

core mixers

**Comment by tebjan** [comment]
closing this, converted the missing two tasks into issues.

**Comment by joreg** [comment]
- [ ] Source: make all non-experimental
- [ ] ColorPalette: Transform input -> float4x4
- [ ] Utils: make ChangeFormat non-experimental
- [ ] Mixer: Make all non-experimental 
- [ ] Blend: GPUIn
- [ ] Remove Mix
- [ ] Filter: make all non-experimental except: FXAA, BrightFilter
- [ ] add experimental GaussianBlur, Bloom
- [ ] remove SimpleBloom

**Comment by joreg** [comment]
- [ ] Blur: bad quality, Strength vs. Control
- [ ] Should Control be Float (one value for all channels) instead of Vector4 (per channel)
- [ ] Make AutoGen mipmap input optional

**Comment by joreg** [comment]
updated all helps
